@startuml

package "application.service" {
  [SendMoneyService]
  [RegisterAccountService]
}

[SendMoneyService] -[hidden]d--> [RegisterAccountService]

package "application.port.out" {
  [LoadAccountRepository]
  [UpdateAccountRepository]
  [CreateAccountRepository]
}

[LoadAccountRepository] -[hidden]d-> [UpdateAccountRepository]
[UpdateAccountRepository] -[hidden]d-> [CreateAccountRepository]

package "adapter.out.persistence" {
  [PersistenceAdapter]
}

[SendMoneyService] -> [LoadAccountRepository]
[SendMoneyService] -> [UpdateAccountRepository]
[RegisterAccountService] -> [CreateAccountRepository]

[LoadAccountRepository]   <|-d- [PersistenceAdapter]
[UpdateAccountRepository] <|-r- [PersistenceAdapter]
[CreateAccountRepository] <|-u- [PersistenceAdapter]

@enduml